#!/bin/bash
#this script will create and manage user access on redhat and centos linux servers
echo " you are welcome to valley bank"
echo " enter your name"
read name"
echo "enter your password"
read password
if [ $password == 1234 ]
then
echo "$password is successfully validated"
else
echo "wrong password entered"
fi

